import AppKit
import Foundation
import Testing
@testable import SayKuku

@Suite("Text write verification")
struct TextWriteVerificationTests {
    @Test("insertion builds the exact expected field value")
    func insertion() {
        let snapshot = target(value: "你好世界", range: CFRange(location: 2, length: 0))
        #expect(TextInteraction.expectedValue(afterWriting: "，", to: snapshot) == "你好，世界")
    }

    @Test("selection replacement uses UTF-16 accessibility ranges")
    func replacement() {
        let snapshot = target(value: "A😀BC", range: CFRange(location: 1, length: 2))
        #expect(TextInteraction.expectedValue(afterWriting: "好", to: snapshot) == "A好BC")
    }

    @Test("dictation joins ASCII words without changing Chinese or punctuation")
    func dictationSpacing() {
        #expect(DictationTextJoiner.join("nice", to: target(value: "helloWorld", range: CFRange(location: 5, length: 0))) == " nice ")
        #expect(DictationTextJoiner.join("世界", to: target(value: "你好。", range: CFRange(location: 2, length: 0))) == "世界")
        #expect(DictationTextJoiner.join("B", to: target(value: "A😀C", range: CFRange(location: 3, length: 0))) == "B ")
        #expect(DictationTextJoiner.join("hello", to: target(value: nil, range: nil)) == "hello")
    }

    @Test("invalid accessibility ranges cannot be treated as verified")
    func invalidRange() {
        let snapshot = target(value: "abc", range: CFRange(location: 4, length: 0))
        #expect(TextInteraction.expectedValue(afterWriting: "x", to: snapshot) == nil)
    }

    @Test("unreadable accessibility state is not treated as verifiable")
    func unreadableTarget() {
        let snapshot = target(value: nil, range: nil)
        #expect(TextInteraction.expectedValue(afterWriting: "text", to: snapshot) == nil)
    }

    @Test("clipboard snapshots preserve every pasteboard type")
    @MainActor
    func clipboardSnapshot() {
        let pasteboard = NSPasteboard(name: .init("SayKukuTests.TextWriteVerification"))
        let customType = NSPasteboard.PasteboardType("com.saykuku.tests.custom")
        let item = NSPasteboardItem()
        item.setString("original", forType: .string)
        item.setData(Data([0x01, 0x02, 0x03]), forType: customType)
        pasteboard.clearContents()
        pasteboard.writeObjects([item])

        let snapshot = TextInteraction.snapshot(of: pasteboard)
        pasteboard.clearContents()
        pasteboard.setString("temporary", forType: .string)
        TextInteraction.restore(snapshot, to: pasteboard)

        #expect(pasteboard.string(forType: .string) == "original")
        #expect(pasteboard.data(forType: customType) == Data([0x01, 0x02, 0x03]))
        pasteboard.releaseGlobally()
    }

    @Test("clipboard backup skips file promises and extra image renditions")
    func clipboardBackupTypes() {
        let custom = NSPasteboard.PasteboardType("com.saykuku.tests.custom")
        let promise = NSPasteboard.PasteboardType("com.apple.pasteboard.promised-file-url")
        let types = PasteboardPolicy.backupTypes([.string, promise, .tiff, .png, custom, .fileURL])
        #expect(types == [.string, .tiff, custom, .fileURL])
    }

    @Test("concealed or transient clipboard content is private")
    func privateClipboard() {
        #expect(PasteboardPolicy.isPrivate([.string, PasteboardPolicy.concealedType]))
        #expect(PasteboardPolicy.isPrivate([.string, PasteboardPolicy.transientType]))
        #expect(!PasteboardPolicy.isPrivate([.string, PasteboardPolicy.autoGeneratedType]))
        #expect(!PasteboardPolicy.isPrivate([.string]))
    }

    @Test("sensitive apps are matched by explicit bundle ID prefixes")
    func sensitiveApps() {
        #expect(SensitiveApps.contains(bundleID: "com.1password.1password"))
        #expect(SensitiveApps.contains(bundleID: "com.agilebits.onepassword7"))
        #expect(SensitiveApps.contains(bundleID: "com.bitwarden.desktop"))
        #expect(SensitiveApps.contains(bundleID: "org.keepassxc.keepassxc"))
        #expect(SensitiveApps.contains(bundleID: "com.apple.Passwords"))
        #expect(!SensitiveApps.contains(bundleID: "com.example.bankside-notes"))
        #expect(!SensitiveApps.contains(bundleID: "com.example.walletpaper"))
        #expect(!SensitiveApps.contains(bundleID: "com.apple.Safari"))
    }

    @Test("web search encodes every reserved query character")
    func webSearchURL() {
        #expect(AgentActionExecutor.webSearchURL(for: "C++ & Rust")?.absoluteString
            == "https://www.google.com/search?q=C%2B%2B%20%26%20Rust")
        #expect(AgentActionExecutor.webSearchURL(for: "a=b#c?d/e")?.absoluteString
            == "https://www.google.com/search?q=a%3Db%23c%3Fd%2Fe")
        #expect(AgentActionExecutor.webSearchURL(for: "你好 swift-6_x.y~")?.absoluteString
            == "https://www.google.com/search?q=%E4%BD%A0%E5%A5%BD%20swift-6_x.y~")
    }

    @Test("knowledge context only records that saved knowledge is used")
    @MainActor
    func knowledgeContextItem() {
        let items = ContextCollector.collect(
            snapshot: target(value: nil, range: nil),
            selectedTextAllowed: false,
            currentAppAllowed: false,
            windowTitleAllowed: false,
            clipboardAllowed: false,
            browserPageAllowed: false,
            session: nil,
            domains: [],
            customDomainTerms: [],
            knowledge: [
                KnowledgeEntity(name: "WorkBuddy", type: .product),
                KnowledgeEntity(name: "SayKuku", type: .product)
            ],
            isChineseUI: false
        )
        #expect(items.count == 1)
        #expect(items.first?.kind == .knowledge)
        #expect(items.first?.value == "2")
    }

    private func target(value: String?, range: CFRange?) -> TextTargetSnapshot {
        TextTargetSnapshot(
            appPID: 0,
            bundleID: "tests",
            appName: "Tests",
            windowTitle: "",
            windowElement: nil,
            textElement: nil,
            selectedRange: range,
            selectedText: "",
            valueBefore: value,
            isSensitive: false
        )
    }
}
