import AppKit
import UniformTypeIdentifiers

/// Clipboard conventions from nspasteboard.org shared by password managers and clipboard history tools.
enum PasteboardPolicy {
    // Computed so this nonisolated enum holds no global state of a possibly non-Sendable type.
    static var concealedType: NSPasteboard.PasteboardType { .init("org.nspasteboard.ConcealedType") }
    static var transientType: NSPasteboard.PasteboardType { .init("org.nspasteboard.TransientType") }
    static var autoGeneratedType: NSPasteboard.PasteboardType { .init("org.nspasteboard.AutoGeneratedType") }

    /// Secrets and short-lived content are marked by their source and never used as Agent context.
    static func isPrivate(_ types: [NSPasteboard.PasteboardType]) -> Bool {
        types.contains(concealedType) || types.contains(transientType)
    }

    /// Types worth backing up before a temporary paste. Reading a type forces its owner to produce
    /// lazily provided data, so file promises are skipped (they cannot be restored without their
    /// provider anyway) and only the owner's first, preferred image representation is kept instead
    /// of making it render every image format it offers.
    static func backupTypes(_ types: [NSPasteboard.PasteboardType]) -> [NSPasteboard.PasteboardType] {
        var result: [NSPasteboard.PasteboardType] = []
        var hasImage = false
        for type in types where !type.rawValue.localizedCaseInsensitiveContains("promise") {
            if UTType(type.rawValue)?.conforms(to: .image) == true {
                guard !hasImage else { continue }
                hasImage = true
            }
            result.append(type)
        }
        return result
    }
}
